spring:
  application:
    name: wishlist-api
  data:
    mongodb:
      authentication-database: admin
      host: '${MONGO_HOST}'
      database: ${MONGO_DB}'
      port: 27017
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'
  cloud:
    kubernetes:
      secrets:
        name: mongo-secret
      config:
        enabled: true
        sources:
          - namespace: default
            name: mongo-conf
      reload:
        enabled: true
        mode: polling
        period: 1000
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
external-api:
  url-client: ${API_CLIENT_URL}
  get-exists: ${API_CLIENT_GET_EXISTS}
  url-product: ${API_PRODUCT_URL}
  get-product: ${API_PRODUCT_GET_PRODUCT}