spring:
  application:
    name: wishlist-api
  data:
    mongodb:
      authentication-database: admin
      host: '${MONGO_HOST}'
      database: ${MONGO_DB}'
      port: 27017
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'
  cloud:
    kubernetes:
      secrets:
        name: mongo-secret
      config:
        enabled: true
        sources:
          - namespace: default
            name: mongo-conf
      reload:
        enabled: true
        mode: polling
        period: 1000
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
wishlist-support:
  url: ${API_SUPPORT_URL}
  get-exists-client: ${API_SUPPORT_GET_EXISTS_CLIENT}
  get-product: ${API_SUPPORT_GET_PRODUCT}