kind: Service
apiVersion: v1
metadata:
  name: wishlist-api
spec:
  selector:
    app: wishlist-api
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-api
spec:
  selector:
    matchLabels:
      app: wishlist-api
  replicas: 2
  template:
    metadata:
      labels:
        app: wishlist-api
    spec:
      containers:
        - name: wishlist-api
          image: raytottifa/wishlist-api:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-wishlist-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-wishlist-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-wishlist-conf
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-wishlist-conf
                  key: host
            - name: API_CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: wishlist-conf
                  key: external-api-url-client
            - name: API_CLIENT_GET_EXISTS
              valueFrom:
                configMapKeyRef:
                  name: wishlist-conf
                  key: external-api-get-exists
            - name: API_PRODUCT_URL
              valueFrom:
                configMapKeyRef:
                  name: wishlist-conf
                  key: external-api-url-product
            - name: API_PRODUCT_GET_PRODUCT
              valueFrom:
                configMapKeyRef:
                  name: wishlist-conf
                  key: external-api-get-product